build:
  builder: DOCKERFILE
  dockerfilePath: Dockerfile

deploy:
  startCommand: uv run /app/start.sh
  restartPolicyType: ON_FAILURE
  restartPolicyMaxRetries: 10

environments:
  production:
    variables:
      PORT: 8501
      API_BASE_URL: ${{RAILWAY_PUBLIC_DOMAIN}}/api
      OPENAI_RAG_MODEL_API_KEY: ${{OPENAI_RAG_MODEL_API_KEY}}
      OPENAI_RAG_MODEL: gpt-3.5-turbo
      RAG_K: 3
      RAG_SCORE_THRESHOLD: 0.3DOCKERFILE
  dockerfilePath: Dockerfile

deploy:
  startCommand: /app/start.sh
  restartPolicyType: ON_FAILURE
  restartPolicyMaxRetries: 10

environments:
  production:
    variables:
      PORT: 8501
      API_BASE_URL: ${{RAILWAY_PUBLIC_DOMAIN}}/api
      OPENAI_RAG_MODEL_API_KEY: ${{OPENAI_RAG_MODEL_API_KEY}}
      OPENAI_RAG_MODEL: gpt-4
      RAG_K: 3
      RAG_SCORE_THRESHOLD: 0.3
