services:
  - type: web
    name: smart-campus-guide
    runtime: python
    plan: free
    buildCommand: pip install uv && uv sync --frozen
    startCommand: uv run streamlit run streamlit_app.py --server.address=0.0.0.0 --server.port=$PORT
    envVars:
      - key: OPENAI_RAG_MODEL_API_KEY
        sync: false
      - key: API_BASE_URL
        value: https://smart-campus-guide-api.onrender.com
      - key: OPENAI_RAG_MODEL
        value: gpt-4
      - key: RAG_K
        value: 3
      - key: RAG_SCORE_THRESHOLD
        value: 0.3
    
  - type: web
    name: smart-campus-guide-api
    runtime: python
    plan: free
    buildCommand: pip install uv && uv sync --frozen
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_RAG_MODEL_API_KEY
        sync: false
      - key: OPENAI_RAG_MODEL
        value: gpt-4
      - key: RAG_K
        value: 3
      - key: RAG_SCORE_THRESHOLD
        value: 0.3
